# Generated by Django 2.0 on 2020-09-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Pincode',
            field=models.BigIntegerField(blank=True),
        ),
    ]
