# Generated by Django 2.0 on 2020-09-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200903_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Pincode',
        ),
    ]
